#!/bin/bash

if [ x$1 == x ]; then
    echo "Wrong Usage"
    exit -1
fi

if [ x$2 == x ]; then
    name=uoj$1
else
    name=$2
fi

curl -o uoj${1}.zip "http://uoj.ac/download.php?type=problem&id=${1}"

mkdir data/$name
cd data/$name
unzip ../../uoj${1}.zip
rm ../../uoj${1}.zip
cd ../..
touch src/${name}.cpp
